title: Portfolio d'Abdel
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: Abdel Ali DJeral
job: Étudiant en intégration multi-média

phone_number: 438-836-9242
address: Laval, Qc
email: djeabdel0@gmail.com
linkedin_username: Pas de LinkedIn encore
github_username: DjeAbdel0
instagram_username: Pas de instagram
twitter_username: Pas de twitter
facebook_username: Pas de facebook
youtube_username: Pas de youtube
blog_url: djeabdel0.github.io/

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag